### ISSUE TITLE
Check the task measurement quality

### ISSUE THREAD

**Issue by psychelzh** [psychelzh/Behav_EF#14]
Hi @Cynthia1229 we have another task here, that is the measurement quality of each task. For example, the reliability and validity.

**Comment by Cynthia1229** [comment]
Humm, you mean we need choose a better measurement? and we cannot do the
CFA now?

BTW, are you free tommorrow?

2017-10-28 22:27 GMT+08:00 Zhang Liang <notifications@github.com>:

**Comment by psychelzh** [comment]
Not exactly. I mean we should calculate the reliability and validity for each task in the near future. We could have an hour or so to do this tomorrow.

**Comment by psychelzh** [comment]
Referenced to #2

**Comment by psychelzh** [comment]
Close it now. Out of my range.
